### ISSUE TITLE
SDK 2.0 Pitch Bend sensitivity and range should be documented

### ISSUE THREAD

**Issue by dukesrg** [korginc/logue-sdk#63]
It worth to mention explicitly here
https://github.com/korginc/logue-sdk/blame/master/platform/drumlogue/README.md#L326
what is the range and sensitivity for Pitch Bend implied.
One can only assume it is 0-16383 raw for +/- 24 semitones.

**Comment by etienne-korg** [comment]
_Note: SDK 2.0-0 is effectively only the drumlogue SDK. Please refer to it as "drumlogue SDK" rather than by its version._

Some details were added for callback parameters. MIDI related callbacks are essentially directly forwarded as received, but in the case of pitch bend, the lsb and msb are packed into a 14bit value before being forwarded.

Sensitivity remains undefined since the drumlogue does not have pitch bend controls, and the synth units are essentially independent of the other parts, so there's no need to match it to anything else. (On prologue/minilogue xd, the oscillator units run alongside the analog VCOs so in that case pitch bend consistency is more important).
